/* Generated By:JJTree: Do not edit this line. ASTChangeItem.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

public
class ASTChangeItem extends SimpleNode {
  private String m_name;
  private String m_date;

  public ASTChangeItem(int id) {
    super(id);
  }

  public ASTChangeItem(PLE_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setChange(String name, String date) {
    m_name = name;
    m_date = date;
  }

  /*
    (CHANGEITEM (((AUTHOR "Per Leander")(WHEN "20170102 18:18")))))
   */
  public void localToString(StringBuilder buf, String prefix) {
    buf.append(prefix).append("( (Author \"").append(m_name).append("\") ");
    buf.append("(When ").append(m_date).append("\")").append(" )\n");
  }
}
/* JavaCC - OriginalChecksum=290c451c90f273bf1ed2698b99636a3e (do not edit this line) */
