/* Generated By:JJTree: Do not edit this line. ASTDocumentation.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

import java.util.ArrayList;

public class ASTDocumentation extends SimpleNode {
  private String m_description;
  private String m_slogan;
  private int    m_majorVersion;
  private int    m_minorVersion;
  private ArrayList<ASTChangeItem> m_changeItems = new ArrayList();

  public ASTDocumentation(PLE_Parser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
        visitor.visit(this, data);
  }

  public void setDescription(String description) {
    m_description = description;
  }

  public void setVersion(int major, int minor) {
    m_majorVersion = major;
    m_minorVersion = minor;
  }

  public void setSlogan(String slogan) {
    m_slogan = slogan;
  }

  public void addChangeItem(ASTChangeItem item) {
    m_changeItems.add(item);
  }

  /*
  (DOCUMENTATION
    (VERSION 12 24)
    (SLOGAN "bla bla bla")
    (DESCRIPTION "bla bla bla")
    (CHANGEITEM (((AUTHOR "Per Leander")(WHEN "20170102 18:18")))))
   */
  public void localToString(StringBuilder buf, String prefix) {
    buf.append('\n').append(prefix).append("(Version ").append(m_majorVersion).append('.').append(m_minorVersion).append(")\n");
    buf.append(prefix).append("(Slogan \"").append(m_slogan).append("\")\n");
    buf.append(prefix).append("(Description \"").append(m_description).append("\")\n");
    buf.append(prefix).append("(ChangeItems (\n");
    for (ASTChangeItem item : m_changeItems) {
      item.localToString(buf, prefix + "  ");
    }
    buf.append(prefix).append(")");
  }
}
/* JavaCC - OriginalChecksum=646e7c7adf1af8c6e9e83506e25aa33a (do not edit this line) */
