/* Generated By:JJTree: Do not edit this line. ASTDataDictionary.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

import se.kaskware.q10.parser.helper.Reference;

import java.util.List;

public
class ASTDataDictionary extends IdentifyableNode {

  public ASTDataDictionary(int id) {
    super(id);
  }

  public ASTDataDictionary(PLE_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  protected List<Reference> resolveReferences() {
    return super.resolveReferences();
  }
}
/* JavaCC - OriginalChecksum=31d73cbc4ce36e35cd01f32c23de66d6 (do not edit this line) */
