/* Generated By:JJTree: Do not edit this line. ASTLob.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

import se.kaskware.q10.parser.helper.Reference;

import java.util.List;

public
class ASTLob extends IdentifyableNode {

  public ASTLob(int id) {
    super(id);
  }

  public ASTLob(PLE_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  protected List<Reference> resolveReferences() {
    return super.resolveReferences();
  }
}
/* JavaCC - OriginalChecksum=93868e64fed4745d72ffca6b52c663dc (do not edit this line) */
