/* Generated By:JJTree: Do not edit this line. ASTProductLine.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

import se.kaskware.q10.parser.helper.Reference;

import java.util.List;

public
class ASTProductLine extends IdentifyableNode {

  public ASTProductLine(int id) {
    super(id);
  }

  public ASTProductLine(PLE_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  protected List<Reference> resolveReferences() {
    return super.resolveReferences();
  }
}
/* JavaCC - OriginalChecksum=9de7977c3e2940bb7f20ec7ef4e0950e (do not edit this line) */
