/* Generated By:JJTree: Do not edit this line. ASTProduct.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

import se.kaskware.q10.parser.helper.LobReference;
import se.kaskware.q10.parser.helper.ProductLineReference;
import se.kaskware.q10.parser.helper.Reference;

import java.util.List;

public
class ASTProduct extends IdentifyableNode {
  private LobReference m_lobReference;
  private ProductLineReference m_prodLineReference;

  public ASTProduct(int id) {
    super(id);
  }

  public ASTProduct(PLE_Parser parser, int product) {
    super(parser, product);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {
    return  visitor.visit(this, data);
  }

  public void setReference(LobReference reference) {
    m_lobReference = reference;
  }

  public void setReference(ProductLineReference reference) {
    m_prodLineReference = reference;
  }

  protected List<Reference> resolveReferences() {
    List<Reference> aList = super.resolveReferences();
    if (!getLagret().referenceExists(m_lobReference)) aList.add(m_lobReference);
    if (!getLagret().referenceExists(m_prodLineReference)) aList.add(m_prodLineReference);

    return aList;
  }

  /*
    (PRODUCT product_2323
      (DOCUMENTATION
        (VERSION 12 24)
        (SLOGAN "bla bla bla")
        (DESCRIPTION "bla bla bla")
        (CHANGEITEMS (
            ((AUTHOR "Per Leander")(WHEN "20170102 18:18"))
            ((AUTHOR "Stevie Ray") (WHEN "20161222 11:18")))))
      (LOB lob_23424)
      (PRODUCTLINE prodline_2342)
      (RULE rule_1231))
   */
  public void localToString(StringBuilder buf, String prefix) {
    super.localToString(buf, prefix);
    buf.append(prefix).append("(Lob ").append(m_lobReference.getIdentifier()).append(")\n");
    buf.append(prefix).append("(ProductLine ").append(m_prodLineReference.getIdentifier()).append(")\n");
  }
}
/* JavaCC - OriginalChecksum=f46143ff6906daebd4b055ee050b27df (do not edit this line) */
