/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

public
class ASTValue extends SimpleNode {
  private ASTValueString m_valueString;
  private int m_value;

  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(PLE_Parser parser, int id) {
    super(parser, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setValue(ASTValueString value) {
    m_valueString = value;
  }

  public void setValue(int value) {
    m_value = value;
  }
}
/* JavaCC - OriginalChecksum=4e17c51850d63ad520af3b97cf48855d (do not edit this line) */
