/* Generated By:JJTree: Do not edit this line. ASTValueString.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.kaskware.q10.parser;

public
class ASTValueString extends SimpleNode {
  private String m_value;

  public ASTValueString(int id) {
    super(id);
  }

  public ASTValueString(PLE_Parser parser, int id) {
    super(parser, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PLE_ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setValue(String value) {
    m_value = value;
  }
}
/* JavaCC - OriginalChecksum=795da98a4f4ae3d9b1a9d301a51d3a03 (do not edit this line) */
