/* Generated By:JavaCC: Do not edit this line. PLE_ParserTreeConstants.java Version 6.1_2 */
package se.kaskware.q10.parser;

public interface PLE_ParserTreeConstants
{
  public int JJTLAGRET = 0;
  public int JJTLOB = 1;
  public int JJTPRODUCTLINE = 2;
  public int JJTRULE = 3;
  public int JJTDATADICTIONARY = 4;
  public int JJTCOEFFICIENTER = 5;
  public int JJTPRODUCT = 6;
  public int JJTDOCUMENTATION = 7;
  public int JJTVOID = 8;
  public int JJTCHANGEITEM = 9;
  public int JJTVALUEBLE = 10;
  public int JJTVALUE = 11;
  public int JJTVALUESTRING = 12;
  public int JJTVARIABLE = 13;


  public String[] jjtNodeName = {
    "Lagret",
    "Lob",
    "ProductLine",
    "Rule",
    "DataDictionary",
    "Coefficienter",
    "Product",
    "Documentation",
    "void",
    "ChangeItem",
    "Valueble",
    "Value",
    "ValueString",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=c48742aaa98eee142818987484f98253 (do not edit this line) */
