/* Generated By:JavaCC: Do not edit this line. PLE_ParserVisitor.java Version 6.1_2 */
package se.kaskware.q10.parser;

public interface PLE_ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTLagret node, Object data);
  public Object visit(ASTLob node, Object data);
  public Object visit(ASTProductLine node, Object data);
  public Object visit(ASTRule node, Object data);
  public Object visit(ASTDataDictionary node, Object data);
  public Object visit(ASTCoefficienter node, Object data);
  public Object visit(ASTProduct node, Object data);
  public Object visit(ASTDocumentation node, Object data);
  public Object visit(ASTChangeItem node, Object data);
  public Object visit(ASTValueble node, Object data);
  public Object visit(ASTValue node, Object data);
  public Object visit(ASTValueString node, Object data);
  public Object visit(ASTVariable node, Object data);
}
/* JavaCC - OriginalChecksum=3257d32442844d76ddc105fa0699d378 (do not edit this line) */
