/* Generated By:JavaCC: Do not edit this line. PLE_ParserDefaultVisitor.java Version 6.1_2 */
package se.kaskware.q10.parser;

public class PLE_ParserDefaultVisitor implements PLE_ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLagret node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLob node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProductLine node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRule node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDataDictionary node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCoefficienter node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProduct node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDocumentation node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTChangeItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValueble node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValueString node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVariable node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=478e4a9774c28d667f72e8b69bafba87 (do not edit this line) */
